/**
 * Regenerates src/builtin-filters.ts from snip's declarative filters.
 *
 * Usage:
 *   bun scripts/generate-filters.ts /path/to/snip/checkout
 *   bun scripts/generate-filters.ts            # fetches the pinned upstream tag
 *
 * Pinned, not master: the table has to describe the snip the user actually runs.
 * Generating from master once shipped filter rules that no released snip had.
 * Any fetch or parse failure aborts — a partial table is worse than a stale one,
 * because a missing rule silently stops wrapping and a wrong one loses output.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { extractMatchRules, type FilterRule } from "../src/filter-yaml"
import { PINNED_SNIP_VERSION } from "../src/snip-cli"

const REF = `v${PINNED_SNIP_VERSION}`

async function fetchOrThrow(url: string): Promise<Response> {
  const r = await fetch(url, { headers: { "user-agent": "opencode-smartsnip-generate-filters" } })
  if (!r.ok) throw new Error(`GET ${url} → ${r.status} ${r.statusText}`)
  return r
}

async function loadFromGitHub(): Promise<{ name: string; text: string }[]> {
  const list = (await (
    await fetchOrThrow(`https://api.github.com/repos/edouard-claude/snip/contents/filters?ref=${REF}`)
  ).json()) as { name: string; download_url: string }[]
  if (!Array.isArray(list) || list.length === 0) throw new Error(`no filters listed at ${REF}`)
  const out: { name: string; text: string }[] = []
  for (const f of list) {
    if (!f.name.endsWith(".yaml")) continue
    out.push({ name: f.name, text: await (await fetchOrThrow(f.download_url)).text() })
  }
  if (out.length === 0) throw new Error(`no .yaml filters at ${REF}`)
  return out
}

function loadFromDir(dir: string): { name: string; text: string }[] {
  return readdirSync(join(dir, "filters"))
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => ({ name: f, text: readFileSync(join(dir, "filters", f), "utf8") }))
}

const src = process.argv[2]
const files = src ? loadFromDir(src) : await loadFromGitHub()

const rules: FilterRule[] = []
const skipped: string[] = []
for (const f of files) {
  const fileRules = extractMatchRules(f.text)
  if (fileRules.length === 0) skipped.push(f.name)
  rules.push(...fileRules)
}
if (skipped.length > 0) {
  console.error(`no match rule extracted from: ${skipped.join(", ")}`)
  process.exit(1)
}
rules.sort(
  (a, b) =>
    a.command.localeCompare(b.command) || (a.subcommand ?? "").localeCompare(b.subcommand ?? ""),
)

const body = `// GENERATED by scripts/generate-filters.ts from edouard-claude/snip@${REF} filters/*.yaml
// Do not edit by hand. Regenerate with: bun run generate:filters

import type { FilterRule } from "./filter-yaml"

export const BUILTIN_FILTERS: FilterRule[] = ${JSON.stringify(rules, null, 2)}
`
writeFileSync(new URL("../src/builtin-filters.ts", import.meta.url), body)
console.log(`wrote ${rules.length} rules from ${files.length} filters (${REF}) to src/builtin-filters.ts`)
