/**
 * Regenerates src/builtin-filters.ts from snip's declarative filters.
 *
 * Usage:
 *   bun scripts/generate-filters.ts /path/to/snip/checkout
 *   bun scripts/generate-filters.ts            # fetches from GitHub (master)
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { extractMatchRules, type FilterRule } from "../src/filter-yaml"

async function loadFromGitHub(): Promise<{ name: string; text: string }[]> {
  const list = await fetch(
    "https://api.github.com/repos/edouard-claude/snip/contents/filters",
  ).then((r) => r.json() as Promise<{ name: string; download_url: string }[]>)
  const out: { name: string; text: string }[] = []
  for (const f of list) {
    if (!f.name.endsWith(".yaml")) continue
    out.push({ name: f.name, text: await fetch(f.download_url).then((r) => r.text()) })
  }
  return out
}

function loadFromDir(dir: string): { name: string; text: string }[] {
  return readdirSync(join(dir, "filters"))
    .filter((f) => f.endsWith(".yaml"))
    .map((f) => ({ name: f, text: readFileSync(join(dir, "filters", f), "utf8") }))
}

const src = process.argv[2]
const files = src ? loadFromDir(src) : await loadFromGitHub()

const rules: FilterRule[] = []
for (const f of files) {
  const rule = extractMatchRules(f.text)
  if (rule) rules.push(rule)
  else console.warn(`skip (no match rule): ${f.name}`)
}
rules.sort((a, b) => a.command.localeCompare(b.command) || (a.subcommand ?? "").localeCompare(b.subcommand ?? ""))

const banner = `// GENERATED by scripts/generate-filters.ts from edouard-claude/snip filters/*.yaml
// Do not edit by hand. Regenerate with: bun run generate:filters
`
const body = `${banner}
import type { FilterRule } from "./filter-yaml"

export const BUILTIN_FILTERS: FilterRule[] = ${JSON.stringify(rules, null, 2)}
`
writeFileSync(new URL("../src/builtin-filters.ts", import.meta.url), body)
console.log(`wrote ${rules.length} rules to src/builtin-filters.ts`)
