// GENERATED by scripts/generate-filters.ts from edouard-claude/snip filters/*.yaml
// Do not edit by hand. Regenerate with: bun run generate:filters

import type { FilterRule } from "./filter-yaml"

export const BUILTIN_FILTERS: FilterRule[] = [
  {
    "command": "ansible-playbook",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "aws",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "basedpyright",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "biome",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "brew",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "bundle",
    "subcommand": "install",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "build",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "check",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "clippy",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "install",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "nextest",
    "excludeFlags": []
  },
  {
    "command": "cargo",
    "subcommand": "test",
    "excludeFlags": []
  },
  {
    "command": "composer",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "curl",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "df",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "diff",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "docker",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-v"
    ]
  },
  {
    "command": "docker",
    "subcommand": "images",
    "excludeFlags": []
  },
  {
    "command": "docker",
    "subcommand": "logs",
    "excludeFlags": []
  },
  {
    "command": "docker",
    "subcommand": "ps",
    "excludeFlags": []
  },
  {
    "command": "docker-compose",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "dotnet",
    "subcommand": "build",
    "excludeFlags": []
  },
  {
    "command": "dotnet",
    "subcommand": "format",
    "excludeFlags": []
  },
  {
    "command": "dotnet",
    "subcommand": "test",
    "excludeFlags": []
  },
  {
    "command": "du",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "eslint",
    "subcommand": null,
    "excludeFlags": [
      "-f",
      "--format",
      "--version"
    ]
  },
  {
    "command": "fail2ban-client",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "find",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "g++",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "gcc",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "gcloud",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "gh",
    "subcommand": "issue",
    "excludeFlags": []
  },
  {
    "command": "gh",
    "subcommand": "pr",
    "excludeFlags": []
  },
  {
    "command": "gh",
    "subcommand": "run",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "add",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "branch",
    "excludeFlags": [
      "-d",
      "-D",
      "-m",
      "-M",
      "--delete",
      "--move",
      "--copy"
    ]
  },
  {
    "command": "git",
    "subcommand": "commit",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "diff",
    "excludeFlags": [
      "--stat",
      "--name-only",
      "--name-status"
    ]
  },
  {
    "command": "git",
    "subcommand": "fetch",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "log",
    "excludeFlags": [
      "--format",
      "--pretty",
      "--graph",
      "--oneline"
    ]
  },
  {
    "command": "git",
    "subcommand": "pull",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "push",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "show",
    "excludeFlags": [
      "--stat",
      "--format",
      "--pretty",
      "--name-only",
      "--name-status"
    ]
  },
  {
    "command": "git",
    "subcommand": "stash",
    "excludeFlags": []
  },
  {
    "command": "git",
    "subcommand": "status",
    "excludeFlags": [
      "--porcelain",
      "--short",
      "-s"
    ]
  },
  {
    "command": "git",
    "subcommand": "worktree",
    "excludeFlags": []
  },
  {
    "command": "go",
    "subcommand": "build",
    "excludeFlags": []
  },
  {
    "command": "go",
    "subcommand": "test",
    "excludeFlags": [
      "-json",
      "-v",
      "-bench",
      "-run"
    ]
  },
  {
    "command": "go",
    "subcommand": "vet",
    "excludeFlags": []
  },
  {
    "command": "golangci-lint",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "gradle",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "gradlew",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "gradlew.bat",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "grep",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "gt",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "hadolint",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "helm",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "iptables",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "jest",
    "subcommand": null,
    "excludeFlags": [
      "--json",
      "--verbose",
      "--version"
    ]
  },
  {
    "command": "jira",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "jj",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "jq",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "just",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "kubectl",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "kubectl",
    "subcommand": "logs",
    "excludeFlags": []
  },
  {
    "command": "liquibase",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ls",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "make",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "markdownlint",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "mise",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "mix",
    "subcommand": "compile",
    "excludeFlags": []
  },
  {
    "command": "mix",
    "subcommand": "format",
    "excludeFlags": []
  },
  {
    "command": "mvn",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "mypy",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "next",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "npm",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-v"
    ]
  },
  {
    "command": "npx",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "nx",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ollama",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "oxlint",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ping",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "pio",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "pip",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "playwright",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "pnpm",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "pnpm",
    "subcommand": "list",
    "excludeFlags": []
  },
  {
    "command": "poetry",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "pre-commit",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "prettier",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "prisma",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ps",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "psql",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "pytest",
    "subcommand": null,
    "excludeFlags": [
      "--tb=no",
      "--co",
      "--collect-only",
      "--version",
      "-V"
    ]
  },
  {
    "command": "quarto",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "rails",
    "subcommand": "db:migrate",
    "excludeFlags": []
  },
  {
    "command": "rails",
    "subcommand": "routes",
    "excludeFlags": [
      "-g",
      "--grep",
      "-c",
      "--controller"
    ]
  },
  {
    "command": "rake",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "rg",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "rspec",
    "subcommand": null,
    "excludeFlags": [
      "--format",
      "-f",
      "--version",
      "-V"
    ]
  },
  {
    "command": "rsync",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "rubocop",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ruff",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "rustc",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "shellcheck",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "shopify",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "skopeo",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "sops",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "spring-boot",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ssh",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "stat",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "swift",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "systemctl",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "task",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "terraform",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "tofu",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "tree",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "trunk",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "tsc",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "turbo",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "ty",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "uv",
    "subcommand": "add",
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "uv",
    "subcommand": "lock",
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "uv",
    "subcommand": "remove",
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "uv",
    "subcommand": "sync",
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "vitest",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "wc",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "wget",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "xcodebuild",
    "subcommand": null,
    "excludeFlags": [
      "--version",
      "-V"
    ]
  },
  {
    "command": "yadm",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "yamllint",
    "subcommand": null,
    "excludeFlags": []
  },
  {
    "command": "yarn",
    "subcommand": null,
    "excludeFlags": []
  }
]
